### ISSUE TITLE
v2.0 todo list

### ISSUE THREAD

**Issue by JezzaR-The-Proto** [JezzaR-The-Proto/RPGBot#1]
- [ ] Adding guild inventories
- [ ] Adding guild info in an image
- [ ] Adding more "rpg explore" options.
- [ ] Adding 1v1 fights
- [ ] Increase level cap to ~50
- [ ] Finish off help pages

**Comment by JezzaR-The-Proto** [comment]
This is final for what v2.0 updates will have. Nothing more will be added.
